### ISSUE TITLE
Can it support other browser? such as chrome?

### ISSUE THREAD

**Issue by Freed-Wu** [dawsers/LeaderF-firefox#1]
can user change `g:Lf_FirefoxDb` to some path where other browser store the data?

it is an enhancement. Thanks!

**Comment by dawsers** [comment]
Sorry, that wouldn't work. The format of the database is different, and I don't use Chrome, so  I wouldn't be able to maintain it. But of course feel free to fork it and change anything you want to make it work for other browsers. Most of the code aside from the SQL query would be reusable.

**Comment by Freed-Wu** [comment]
Good! let me see.
