### ISSUE TITLE
question about sqlite3

### ISSUE THREAD

**Issue by Freed-Wu** [dawsers/LeaderF-firefox#2]
<https://docs.python.org/3/library/sqlite3.htm> has been 404 not found, and `pip install sqlite3 --user` will found nothing. perhaps this package has changed name?

**Comment by dawsers** [comment]
[python-sqlite3](https://docs.python.org/3/library/sqlite3.html) is now part of the Python standard library, so you don't need to install an additional Python package any more.

Simply verify you have the binary sqlite package installed on your machine by using your package manager, or typing `sqlite3` in the terminal and seeing the `sqlite3` binary is present.

**Comment by Freed-Wu** [comment]
You are right!
